sonar.projectKey=mitchins_light-route
sonar.organization=mitchins
sonar.host.url=https://sonarcloud.io
sonar.sources=Sources
sonar.tests=Tests
sonar.test.inclusions=Tests/**
sonar.exclusions=Examples/**,.build/**,docs/**
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=.build/reports/sonar-generic-coverage.xml